# --- Builder Stage ---
FROM golang:1.24-alpine AS builder

RUN apk add --no-cache git curl bash

WORKDIR /app
COPY go.mod .
COPY go.sum .
RUN go clean --modcache && go mod download && go get -d ./...

COPY . .

WORKDIR /app/cmd/backend
RUN go build -o main .

# --- Runner Stage ---
FROM alpine:latest

WORKDIR /app
COPY --from=builder /app/cmd/backend/main .

EXPOSE 8080

ENTRYPOINT ["./main"]