name: backend

on:
  pull_request:
    branches:
      - preview

jobs:
  backend-format:
    name: Backend Format Check
    runs-on: ubuntu-latest
    env:
      GOTOOLCHAIN: local
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.5
          cache: true

      - name: Verify gofmt compliance
        run: |
          go_files=$(git ls-files '*.go')
          if [ -z "$go_files" ]; then
            exit 0
          fi

          unformatted=$(gofmt -l $go_files)
          if [ -n "$unformatted" ]; then
            echo "The following files are not formatted:" >&2
            echo "$unformatted" >&2
            exit 1
          fi

  backend-lint:
    name: Backend Lint
    runs-on: ubuntu-latest
    needs: backend-format
    env:
      GOTOOLCHAIN: local
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.5
          cache: true

      - name: Run go vet
        run: go vet ./...

  backend-test:
    name: Backend Tests (internal/usecase)
    runs-on: ubuntu-latest
    needs: backend-lint
    env:
      GOTOOLCHAIN: local
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.5
          cache: true

      - name: Run unit tests (internal/usecase)
        run: go test ./internal/usecase/...
